apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: {{ .Values.tranql_varnish.frontend.service_name }}
    spec:
      type: NodePort
      selector:
        app: {{ .Values.tranql_varnish.frontend.app_name }}
      ports:
        - protocol: TCP
          port: {{ .Values.tranql_varnish.port }}
          targetPort: {{ .Values.tranql_varnish.port }}
  - apiVersion: v1
    kind: Service
    metadata:
      name: {{ .Values.tranql_varnish.backplane.service_name }}
    spec:
      type: NodePort
      selector:
        app: {{ .Values.tranql_varnish.backplane.app_name }}
      ports:
        - protocol: TCP
          port: {{ .Values.tranql_varnish.port }}
          targetPort: {{ .Values.tranql_varnish.port }}
kind: List