dist: xenial
language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r tranql/requirements.txt
# command to run tests
script:
  - bin/test
after_success:
  - bin/test_coverage