---
doc : |
  The Translator schema aggregates reasoner schemas. Reasoner schemas
  describe transitions between biolink-model types. These transitions are
  expressed as predicates, also from the biolink-model. 
schema:
  robokop :
    doc: |
      The Robokop reasoner provides an endpoint returning the transitions it supports.
    url: /graph/gamma/quick
    schema: http://robokop.renci.org:6010/api/predicates
  icees :
    doc: |
      For now, we provide a simple schema for one endpoint modeling the ICEES clinical
      reasoners capabilities. It would be good to get an ICEES reasoner endpoint
      capable of managing general question graphs.
    url: /clinical/cohort/disease_to_chemical_exposure
    schema:
      population_of_individual_organisms :
        drug_exposure :
          - population_to_drug_exposure
        chemical_substance :
          - population_to_drug_exposure
  implicit_conversion:
    doc: |
      Implicit conversions bridge segments of a query. If one reasoner can return a drug exposure
      and another can take a chemical substance, implicit conversion provides a bridge between these
      types allowing the implementation of complex queries.
    url: /implicit_conversion
    schema:
      drug_exposure:
        chemical_substance:
          - is_a
          
