---
doc : |
  The Translator schema aggregates reasoner schemas. Reasoner schemas
  describe transitions between biolink-model types. These transitions are
  expressed as predicates, also from the biolink-model.
schema:
  # indigo :
  #   doc: |
  #     The Indigo reasoner provides an endpoint for returning the transitions it supports.
  #   url: /graph/indigo
  #   schema: https://indigo.ncats.io/reasoner/api/v1/predicates
  robokop :
    doc: |
      The Robokop reasoner provides an endpoint returning the transitions it supports.
    url: /graph/gamma/quick
    schema: http://robokop.renci.org:6010/api/predicates
  icees :
    doc: |
      We point at the ICEES clinical reasoners schema endpoint, mapping questions it is
      capable of answering. For backplane URLs, the protocol, host, and port are implicit.
      The ICEES schema endpoint requires additional formatting and handling which we take care
      of in the backplane wrapper.
    url: /clinical/cohort/disease_to_chemical_exposure?provider=icees
    schema: /clincial/icees/schema?provider=icees

  icees3_and_epr:
    doc: |
      We point at the ICEES clinical reasoners schema endpoint, mapping questions it is
      capable of answering. For backplane URLs, the protocol, host, and port are implicit.
      The ICEES schema endpoint requires additional formatting and handling which we take care
      of in the backplane wrapper.
    url: /clinical/cohort/disease_to_chemical_exposure?provider=icees3_and_epr
    schema: /clincial/icees/schema?provider=icees3_and_epr

  automat :
    doc: |
      Automat is a registry of several KPs. We have a backplane url to route to each of its entries.
      When constracting our schema, we could ask for what is available on automat and add each KP's
      graph schema to our schema.
    registry: automat
    registry_url: https://automat.renci.org
    url: /graph/automat
  rtx :
    doc: |
      The Rtx reasoner provides an endpoint returning the transitions it supports.
    url: /graph/rtx
    schema: https://rtx.ncats.io/beta/api/rtx/v1/predicates
  implicit_conversion:
    doc: |
      Implicit conversions bridge segments of a query. If one reasoner can return a drug exposure
      and another can take a chemical substance, implicit conversion provides a bridge between these
      types allowing the implementation of complex queries.
    url: /implicit_conversion
    schema:
      drug_exposure:
        chemical_substance:
          - is_a
