version: "3"
services:
  backplane:
    image: renciorg/tranql-base:0.32
    entrypoint: /usr/local/bin/gunicorn --workers=2 --bind=0.0.0.0:$BACKPLANE_PORT --name=backplane --timeout=600 tranql.backplane.server:app
    ports:
      - "${BACKPLANE_PORT}:${BACKPLANE_PORT}"
  tranql:
    image: renciorg/tranql-app:0.32
    environment:
      - BACKPLANE=http://varnish_backplane:8080
#      - BACKPLANE=http://backplane:8099  # Uncomment this line to avoid using cache.
      - APP_PORT
      - USE_REGISTRY=TRUE
    entrypoint: /usr/local/bin/gunicorn --workers=2 --bind=0.0.0.0:$APP_PORT --name=tranql --timeout=600 tranql.api:app
    ports:
      - "${APP_PORT}:${APP_PORT}"
  varnish_frontend:
    image: tranql-varinish-local
#    build:
#      context: tranql-varnish
    container_name: tranql_frontend_cache
    volumes:
      - ../varnish-cache/frontend.config.vcl:/etc/varnish/default.vcl
    ports:
      - "8080:8080"
  varnish_backplane:
    image: tranql-varinish-local #renciorg/tranql-varnish
#    build:
#      context: tranql-varnish
    container_name: tranql_backplane_cache
    volumes:
      - ../varnish-cache/backplane.config.vcl:/etc/varnish/default.vcl
    ports:
      - "8081:8080"
networks:
  default:
    external:
      name: ${COMPOSE_PROJECT_NAME}_default
