apiVersion: v1
kind: Pod
metadata:
  name: tranql-frontend
  labels:
    service: tranql-frontend-service
    app: tranql-frontend
spec:
  terminationGracePeriodSeconds: 10
  containers:
  - name: tranql-app
    image: greentranslator/tranql-app
    command: [ "/usr/local/bin/gunicorn", "--workers=2", "--bind=0.0.0.0:8001", "--timeout=600", "tranql.api:app" ]
    ports:
      - containerPort: 8001
        name: http
    env:
      - name: APP_PORT
        value: "8001"
      - name: BACKPLANE
        value: http://tranql-backend-service.bennettc.svc.stars-cluster.local:8099
    resources:
      requests:
        memory: 200Mi
      limits:
        memory: 1Gi
  restartPolicy: OnFailure
